[phases.setup]
nixPkgs = ['python39', 'texlive.combined.scheme-medium', 'curl']

[phases.install]
cmds = ['pip install -r tailorcv-backend/requirements.txt']

[phases.build]
cmds = ['cp -r tailorcv-backend/* .']

[start]
cmd = 'python app.py'