[build]
builder = "nixpacks"

[deploy]
startCommand = "python tailorcv-backend/app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10