[build]
builder = "nixpacks"

[deploy]
startCommand = "python app_ultra_minimal.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build.env]
PYTHONUNBUFFERED = "1"