[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd tailorcv-backend && python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10