import os
import tempfile
import subprocess
from typing import Dict, Any
from jinja2 import Environment, FileSystemLoader

class LaTeXService:
    def __init__(self):
        self.template_dir = os.path.join(os.path.dirname(__file__), '..', 'templates')
        self.jinja_env = Environment(loader=FileSystemLoader(self.template_dir))
    
    def generate_pdf(self, resume_data: Dict[str, Any], is_premium: bool = False) -> bytes:
        """
        Generate PDF from resume data using LaTeX
        """
        try:
            # Choose template based on premium status
            template_name = 'premium_resume.tex' if is_premium else 'free_resume.tex'
            
            # Generate LaTeX content
            latex_content = self._generate_latex_content(resume_data, template_name, is_premium)
            
            # Compile LaTeX to PDF
            pdf_content = self._compile_latex_to_pdf(latex_content)
            
            return pdf_content
            
        except Exception as e:
            raise Exception(f"Failed to generate PDF: {str(e)}")
    
    def _generate_latex_content(self, resume_data: Dict[str, Any], template_name: str, is_premium: bool) -> str:
        """
        Generate LaTeX content from resume data and template
        """
        try:
            # Load template
            template = self.jinja_env.get_template(template_name)
            
            # Prepare data for template
            template_data = {
                'personal_info': resume_data.get('personalInfo', {}),
                'summary': resume_data.get('summary', ''),
                'skills': resume_data.get('skills', []),
                'experience': resume_data.get('experience', []),
                'education': resume_data.get('education', []),
                'projects': resume_data.get('projects', []),
                'certifications': resume_data.get('certifications', []),
                'is_premium': is_premium,
                'show_watermark': not is_premium
            }
            
            # Render template
            latex_content = template.render(template_data)
            
            return latex_content
            
        except Exception as e:
            # Fallback to basic template if template rendering fails
            return self._generate_fallback_latex(resume_data, is_premium)
    
    def _compile_latex_to_pdf(self, latex_content: str) -> bytes:
        """
        Compile LaTeX content to PDF using pdflatex
        """
        with tempfile.TemporaryDirectory() as temp_dir:
            # Write LaTeX content to file
            tex_file = os.path.join(temp_dir, 'resume.tex')
            with open(tex_file, 'w', encoding='utf-8') as f:
                f.write(latex_content)
            
            try:
                # Run pdflatex
                result = subprocess.run([
                    'pdflatex',
                    '-interaction=nonstopmode',
                    '-output-directory=' + temp_dir,
                    tex_file
                ], capture_output=True, text=True, timeout=60)
                
                if result.returncode != 0:
                    # If pdflatex fails, try with xelatex
                    result = subprocess.run([
                        'xelatex',
                        '-interaction=nonstopmode',
                        '-output-directory=' + temp_dir,
                        tex_file
                    ], capture_output=True, text=True, timeout=60)
                
                if result.returncode != 0:
                    raise Exception(f"LaTeX compilation failed: {result.stderr}")
                
                # Read generated PDF
                pdf_file = os.path.join(temp_dir, 'resume.pdf')
                if not os.path.exists(pdf_file):
                    raise Exception("PDF file was not generated")
                
                with open(pdf_file, 'rb') as f:
                    return f.read()
                    
            except subprocess.TimeoutExpired:
                raise Exception("LaTeX compilation timed out")
            except FileNotFoundError:
                raise Exception("LaTeX compiler not found. Please install pdflatex or xelatex.")
    
    def _generate_fallback_latex(self, resume_data: Dict[str, Any], is_premium: bool) -> str:
        """
        Generate basic LaTeX content as fallback
        """
        personal_info = resume_data.get('personalInfo', {})
        name = personal_info.get('name', 'Your Name')
        email = personal_info.get('email', 'your.email@example.com')
        phone = personal_info.get('phone', '(555) 123-4567')
        location = personal_info.get('location', 'Your City, State')
        
        watermark = '' if is_premium else '\\usepackage{background}\n\\backgroundsetup{scale=1,color=black,opacity=0.1,angle=45,contents={Generated by TailorCV}}'
        
        latex_content = f"""
\\documentclass[letterpaper,11pt]{{article}}
\\usepackage[left=0.75in,top=0.6in,right=0.75in,bottom=0.6in]{{geometry}}
\\usepackage{{titlesec}}
\\usepackage{{enumitem}}
\\usepackage{{hyperref}}
\\usepackage{{xcolor}}
{watermark}

\\pagestyle{{empty}}
\\setlength{{\\tabcolsep}}{{0em}}

\\titleformat{{\\section}}{{\\vspace{{-4pt}}\\scshape\\raggedright\\large\\bfseries}}{{}}{{0em}}{{}}[\\color{{black}}\\titlerule \\vspace{{-5pt}}]

\\begin{{document}}

\\begin{{center}}
    {{\\Huge \\scshape {name}}} \\\\ \\vspace{{1pt}}
    \\small {phone} $|$ \\href{{mailto:{email}}}{{{email}}} $|$ {location}
\\end{{center}}

\\section{{Summary}}
{resume_data.get('summary', 'Professional summary goes here.')}

\\section{{Skills}}
\\begin{{itemize}}[leftmargin=0.15in, label={{$\\bullet$}}]
"""
        
        # Add skills
        for skill in resume_data.get('skills', []):
            latex_content += f"    \\item {skill}\n"
        
        latex_content += """
\\end{itemize}

\\section{Experience}
"""
        
        # Add experience
        for exp in resume_data.get('experience', []):
            company = exp.get('company', '')
            title = exp.get('title', '')
            start_date = exp.get('startDate', '')
            end_date = exp.get('endDate', '')
            
            latex_content += f"""
\\textbf{{{title}}} \\hfill {start_date} -- {end_date} \\\\
\\textit{{{company}}} \\\\
\\begin{{itemize}}[leftmargin=0.15in, label={{$\\bullet$}}]
"""
            
            for desc in exp.get('description', []):
                latex_content += f"    \\item {desc}\n"
            
            latex_content += "\\end{itemize}\n"
        
        latex_content += """
\\section{Education}
"""
        
        # Add education
        for edu in resume_data.get('education', []):
            degree = edu.get('degree', '')
            institution = edu.get('institution', '')
            start_date = edu.get('startDate', '')
            end_date = edu.get('endDate', '')
            
            latex_content += f"""
\\textbf{{{degree}}} \\hfill {start_date} -- {end_date} \\\\
\\textit{{{institution}}} \\\\
"""
        
        # Add projects if available
        if resume_data.get('projects'):
            latex_content += """
\\section{Projects}
"""
            
            for project in resume_data.get('projects', []):
                name = project.get('name', '')
                description = project.get('description', '')
                technologies = ', '.join(project.get('technologies', []))
                
                latex_content += f"""
\\textbf{{{name}}} \\\\
{description} \\\\
\\textit{{Technologies: {technologies}}} \\\\
"""
        
        latex_content += """
\\end{document}
"""
        
        return latex_content
    
    def validate_latex_installation(self) -> bool:
        """
        Check if LaTeX is properly installed
        """
        try:
            result = subprocess.run(['pdflatex', '--version'], 
                                  capture_output=True, text=True, timeout=10)
            return result.returncode == 0
        except (subprocess.TimeoutExpired, FileNotFoundError):
            try:
                result = subprocess.run(['xelatex', '--version'], 
                                      capture_output=True, text=True, timeout=10)
                return result.returncode == 0
            except (subprocess.TimeoutExpired, FileNotFoundError):
                return False
    
    def get_available_templates(self) -> list:
        """
        Get list of available LaTeX templates
        """
        templates = []
        
        if os.path.exists(self.template_dir):
            for file in os.listdir(self.template_dir):
                if file.endswith('.tex'):
                    templates.append(file)
        
        return templates